---
title: "Final lab-Shen"
author: "Jiaxin Shen"
format: html
editor: visual
---

## Github link: <https://github.com/jiaxin0816/science_fiction>

```{r}
here::i_am("science_fiction.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)
library(stringr)
theme_set(theme_bw())
```

## Data Loading

```{r}
Planets <- vroom(here("data", "LIST+PLANETS.csv"))
```

## Verify validity
```{r}
Planets |> count()
Planets |> ncol()
are_numeric <- sapply(Planets, is.numeric)
Planets <- Planets |> mutate_at(vars(4:6), ~ str_replace_all(., ",", "."))
Planets <- Planets |> mutate_at(vars(4:6), as.numeric)
```

## Question 4
```{r}
missing_count <- Planets |>
  summarise(across(everything(), ~ sum(is.na(.))))
columns_with_missing <- sum(colSums(is.na(Planets)) > 0)
```


```{r}
Info <- data.frame(file_name='Planets',ob_number=nrow(Planets),va_number=ncol(Planets),columns_with_missing)
Info2 <- cbind(Info, missing_count)
knitr::kable(Info2)
```

##  Question 5

```{r warning=FALSE}
ggplot(Planets, aes(x = Mass, y = RADIUS)) +
  geom_point() +
  labs(x = "Mass of the Planet", y = "Radius of the Planet") +
  ggtitle("Relationship between Planet Radius and Mass")
```

## Question 6

```{r}
max_values <- Planets %>% 
  summarise(across(4:6, .fns = max, na.rm = TRUE))
min_values <- Planets %>% 
  summarise(across(4:6, .fns = min, na.rm = TRUE)) 

```


```{r}

```


## Question 7
```{r}
terrain_df <- Planets %>%
  select(Planet_number, `terrain type`) %>%
  mutate(`terrain type` = str_split(`terrain type`, ": ")) %>%
  unnest(cols = `terrain type`) %>%
  reframe(Planet_number, `terrain type`)
terrain_df_sp <- separate(terrain_df,`terrain type`, into = c("terrain type1", "terrain type2", "terrain type3","terrain type4","terrain type5","terrain type6","terrain type7","terrain type8","terrain type9","terrain type10","terrain type11"), sep = ":")
```

```{r}
climate_df <- Planets %>%
  select(Planet_number, `TYPE OF CLIMATE`) %>%
  mutate(`TYPE OF CLIMATE` = str_split(`TYPE OF CLIMATE`, ": ")) %>%
  unnest(cols = `TYPE OF CLIMATE`) %>%
  reframe(Planet_number, `TYPE OF CLIMATE`)
climate_df_sp <- separate(climate_df,`TYPE OF CLIMATE`, into = c("climate type1", "climate type2", "climate type3","climate type4","climate type5","climate type6","climate type7"), sep = ":")
```

## Question 8
```{r}

```

## Question 9


## Question 10

```{r}
Stars <- vroom(here("data", "LIST+Stars.csv"))
```

```{r}
Stars |> count()
Stars |> ncol()
are_numeric3 <- sapply(Stars, is.numeric)
Stars <- Stars |> mutate_at(vars(5:7), ~ str_replace_all(., ",", "."))
Stars <- Stars |> mutate_at(vars(5:7), as.numeric)
are_numeric4 <- sapply(Stars, is.numeric)
```

## Question 11
```{r}
planets_no_star <- Planets %>%
  filter(!(star_idx %in% Stars$star_idx))
N_star <- nrow(planets_no_star)
```

## Question 12
```{r}
Stars$ temperature_class <- substr(Stars$`Stellar Class`, 1, 1)
Stars$ temperature <- substr(Stars$`Stellar Class`, 2, 2)
Stars$spectral_classification <- substr(Stars$`Stellar Class`, 3, 3)
```

## Question 12
```{r}
ggplot(Stars, aes(x = temperature_class)) +
  geom_bar(fill = "skyblue", color = "black") +
  labs(title = "Distribution of Stars by Temperature Class", 
       x = "Temperature Class", y = "Count") +
  theme_minimal()
```

